name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e .[dev]

    - name: Build user documentation
      run: |
        cd docs
        make html
        touch _build/html/.nojekyll

    - name: Build developer documentation
      run: |
        cd dev-docs
        make html
        touch _build/html/.nojekyll

    - name: Deploy user documentation
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        destination_dir: docs
        force_orphan: false

    - name: Deploy developer documentation
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dev-docs/_build/html
        destination_dir: dev-docs
        force_orphan: false